### ISSUE TITLE
Status styles

### ISSUE THREAD

**Issue by aharris88** [trevordmiller/nova-example-dotfiles#1]
On the example `.tmux.conf`, you might want to add:

    set -g status-style 'fg=brightblack, bg=black'

When I don't have this line, it looks like this:

![screen shot 2016-09-21 at 9 38 25 am](https://cloud.githubusercontent.com/assets/3266363/18718030/4145a7c6-7fdf-11e6-8678-aa315e64e1a2.png)

instead of this:

![screen shot 2016-09-21 at 9 38 47 am](https://cloud.githubusercontent.com/assets/3266363/18718038/47547bc4-7fdf-11e6-902a-9078e0baceb1.png)

**Comment by trevordmiller** [comment]
Good tip! I didn't notice that because I have my status line disabled. Thanks for letting me know, I'll submit a PR.
